  
export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";

export const SIGNOUT_FETCHING = "SIGNOUT_FETCHING";
export const SIGNOUT_FULFILLED = "SIGNOUT_FULFILLED";
export const SIGNOUT_REJECTED = "SIGNOUT_REJECTED";