export const GET_BUILDINGS_FETCHING = "GET_BUILDINGS_FETCHING";
export const GET_BUILDINGS_FULLFILLED = "GET_BUILDINGS_FULLFILLED";
export const GET_BUILDINGS_REJECTED = "GET_BUILDINGS_REJECTED";

export const ADD_BUILDING_FETCHING = "ADD_BUILDING_FETCHING";
export const ADD_BUILDING_FULLFILLED = "ADD_BUILDING_FULLFILLED";
export const ADD_BUILDING_REJECTED = "ADD_BUILDING_REJECTED";

export const DELETE_BUILDING_FETCHING = "DELETE_BUILDING_FETCHING";
export const DELETE_BUILDING_FULLFILLED = "DELETE_BUILDING_FULLFILLED";
export const DELETE_BUILDING_REJECTED = "DELETE_BUILDING_REJECTED";

export const UPDATE_BUILDING_FETCHING = "UPDATE_BUILDING_FETCHING";
export const UPDATE_BUILDING_FULLFILLED = "UPDATE_BUILDING_FULLFILLED";
export const UPDATE_BUILDING_REJECTED = "UPDATE_BUILDING_REJECTED";
